[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[context.production]
  publish = "output/"
  command = "make publish"
  


[dev]
  command = "svelte-kit dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
